Repository ISG-ICS/cloudberry, pull requests merged in 2019-03, with the labels that each got.

#671 Increase buffer size to improve geoTagger's performance
  examples/twittermap/noah/src/main/scala/edu/uci/ics/cloudberry/noah/TwitterJSONTagToADM.scala
Labels: back-end

#672 [Script] Only alert when the total count is not changed during the last one hour
  examples/twittermap/script/berryGuard.sh
Labels: enhancement

#669 [FrontEnd] Add logic to reconnect websocket if error occurs
  examples/twittermap/web/public/javascripts/common/cloudberry-client.js
  examples/twittermap/web/public/javascripts/common/services.js
  examples/twittermap/web/public/javascripts/map/pinmap.js
  examples/twittermap/web/public/javascripts/sidebar/controllers.js
  examples/twittermap/web/public/javascripts/timeseries/controllers.js
Labels: enhancement, front-end
