Repository ISG-ICS/cloudberry, pull requests merged in 2020-03, with the labels that each got.

#731 [Fix bug] Fix tweet url composition with user.id as part of the link.
  examples/twittermap/web/public/javascripts/map/pinmap.js
Labels: bug

#767 Enable Google Analytics
  examples/coronavirustwittermap/web/app/controllers/TwitterMapApplication.scala
  examples/coronavirustwittermap/web/app/views/twittermap/main.scala.html
  examples/coronavirustwittermap/web/conf/application.conf
  examples/coronavirustwittermap/web/conf/production.conf
Labels: enhancement

#770 Fix the popup window bug on Safari
  examples/coronavirustwittermap/web/public/javascripts/map/countmap.js
Labels: fix
